AllCops:
  Include:
    - "**/Rakefile"
    - "**/config.ru"
    - "app/**/*.rb"
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "Gemfile"
  TargetRubyVersion: 2.5.2

Metrics/LineLength:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_
    - have_

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - lib/tasks/**/*.rake

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb
