# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1b9fa53dacaaee8275e2e807e0e8c36e93bcb58c284a9377c9fc9e62d5c24d96ecc15fd7abcba94b2e4b262649afa46803bb7e425e0d21c7d174626ed76047e
  mailer_from_email: development@includebraga.org
  mailer_from_name: Development Santa
  mailer_host: localhost:5000
  mailer_domain: localhost:5000

test:
  secret_key_base: e5bd45cd9c9c3c522ba707fa0ec1ba3d70cc4d9a20972838694f085cb1b495f26c3c7a3e182da1c2ce9357d9d957caea2d8d8ba1eb61eec09deabcce5057805e
  mailer_from_email: test@includebraga.org
  mailer_from_name: Test Santa
  mailer_host: localhost:5000
  mailer_domain: localhost:5000

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_from_email: <%= ENV["MAILER_FROM_EMAIL"] %>
  mailer_from_name: <%= ENV["MAILER_FROM_NAME"] %>
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_host: <%= ENV["MAILER_HOST"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_from_email: <%= ENV["MAILER_FROM_EMAIL"] %>
  mailer_from_name: <%= ENV["MAILER_FROM_NAME"] %>
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_host: <%= ENV["MAILER_HOST"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
